### ISSUE TITLE
Stuck on language

### ISSUE THREAD

**Issue by rtfm87** [noes14155/Telegrambot-with-GPT4free#14] opened 2023-06-25 15:36 UTC
Hi, i get the following error on selecting language:
patcher/dispatcher.py:407> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/app/./main.py", line 204, in chat
    language = available_lang['languages'].get(db.get_settings(call.from_user.id), available_lang['languages']['en'])
TypeError: string indices must be integers

**Comment by MLNekit** [comment] 2023-06-25 17:21
The problem is in the code, it will be fixed in the next few days

**Comment by MLNekit** [comment] 2023-06-25 20:42
Check if this bug is in the new version of the bot

**Closed** 2023-07-04 21:01 UTC
